name: gt06_gateway
description: "GT06 Gateway Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências principais
  geolocator: ^13.0.2
  usb_serial: ^0.5.2
  shared_preferences: ^2.3.2
  
  # Serviço de background
  flutter_background_service: ^5.0.5
  
  # Dependências de UI
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true