name: gt06_gateway
description: "GT06 Gateway Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # para funcionar background
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1
  minimize_app: ^1.0.3

  # GPS e Localização
  geolocator: ^13.0.2
  
  # USB Serial para Arduino
  usb_serial: ^0.5.2
  
  # Estado e UI
  provider: ^6.1.2
  
  # Utilidades
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
